language: node_js
node_js:
  - "7"
notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/1032b999beaa63e3b59a851a5c2c4250010b4a6088e76e5074d62696651989e3
    on_success: change # default: always
    on_failure: always # default: always
    on_start:   change # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always